#!/bin/sh

function copy {
	B=${2:-"$1"}
	cp ../trunk/$1 $B.wiki
}

copy README
copy INSTALL
copy TODO
copy ChangeLog
copy COPYING
copy docs/example.py EXAMPLETMP

rm EXAMPLE.wiki
echo "{{{" >> EXAMPLE.wiki
cat EXAMPLETMP.wiki >> EXAMPLE.wiki
echo "}}}" >> EXAMPLE.wiki
rm EXAMPLETMP.wiki

